/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasAtendidasRouteImport } from './routes/areas-atendidas'
import { Route as LocacaoDeCacambaRouteImport } from './routes/locacao-de-cacamba'
import { Route as RetiradaDeEntulhoRouteImport } from './routes/retirada-de-entulho'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAtendidasRoute = AreasAtendidasRouteImport.update({
  id: '/areas-atendidas',
  path: '/areas-atendidas',
  getParentRoute: () => rootRouteImport,
} as any)
const LocacaoDeCacambaRoute = LocacaoDeCacambaRouteImport.update({
  id: '/locacao-de-cacamba',
  path: '/locacao-de-cacamba',
  getParentRoute: () => rootRouteImport,
} as any)
const RetiradaDeEntulhoRoute = RetiradaDeEntulhoRouteImport.update({
  id: '/retirada-de-entulho',
  path: '/retirada-de-entulho',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas-atendidas': typeof AreasAtendidasRoute
  '/locacao-de-cacamba': typeof LocacaoDeCacambaRoute
  '/retirada-de-entulho': typeof RetiradaDeEntulhoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas-atendidas': typeof AreasAtendidasRoute
  '/locacao-de-cacamba': typeof LocacaoDeCacambaRoute
  '/retirada-de-entulho': typeof RetiradaDeEntulhoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas-atendidas': typeof AreasAtendidasRoute
  '/locacao-de-cacamba': typeof LocacaoDeCacambaRoute
  '/retirada-de-entulho': typeof RetiradaDeEntulhoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/areas-atendidas' | '/locacao-de-cacamba' | '/retirada-de-entulho'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/areas-atendidas' | '/locacao-de-cacamba' | '/retirada-de-entulho'
  id:
    | '__root__'
    | '/'
    | '/areas-atendidas'
    | '/locacao-de-cacamba'
    | '/retirada-de-entulho'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasAtendidasRoute: typeof AreasAtendidasRoute
  LocacaoDeCacambaRoute: typeof LocacaoDeCacambaRoute
  RetiradaDeEntulhoRoute: typeof RetiradaDeEntulhoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-atendidas': {
      id: '/areas-atendidas'
      path: '/areas-atendidas'
      fullPath: '/areas-atendidas'
      preLoaderRoute: typeof AreasAtendidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locacao-de-cacamba': {
      id: '/locacao-de-cacamba'
      path: '/locacao-de-cacamba'
      fullPath: '/locacao-de-cacamba'
      preLoaderRoute: typeof LocacaoDeCacambaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retirada-de-entulho': {
      id: '/retirada-de-entulho'
      path: '/retirada-de-entulho'
      fullPath: '/retirada-de-entulho'
      preLoaderRoute: typeof RetiradaDeEntulhoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasAtendidasRoute: AreasAtendidasRoute,
  LocacaoDeCacambaRoute: LocacaoDeCacambaRoute,
  RetiradaDeEntulhoRoute: RetiradaDeEntulhoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
